Repository KarmaKamikaze/P2-Project, pull requests merged in 2021-04, with the labels that each got.

#94 Added BIG graph and dark mode
  node/PublicResources/graphPresets/GraphBig.cyjs
  node/PublicResources/html/visualization.html
  node/PublicResources/js/cytoStylesheet.js
  node/PublicResources/js/darkMode.js
  node/PublicResources/js/graphCore.js
Labels: feature

#104 Feature/order generation
  node/PublicResources/html/visualization.html
  node/PublicResources/js/aStar.js
  node/PublicResources/js/cytoStylesheet.js
  node/PublicResources/js/dijkstra.js
  node/PublicResources/js/graphCore.js
  node/PublicResources/js/graphHelper.js
  node/PublicResources/js/greedyBestFirstSearch.js
  node/PublicResources/js/orderGeneration.js
  node/PublicResources/js/pathModules.js
Labels: feature

#111 Feature/heat gen
  node/PublicResources/js/cytoStylesheet.js
  node/PublicResources/js/graphCore.js
  node/PublicResources/js/graphHelper.js
  node/PublicResources/js/heatGeneration.js
  node/PublicResources/js/orderGeneration.js
Labels: feature

#124 feature/separateCytostyleOptions
  node/PublicResources/css/style.css
  node/PublicResources/js/cytoStylesheet.js
  node/PublicResources/js/darkMode.js
  node/PublicResources/js/dynamicPageGeneration.js
  node/PublicResources/js/graphCore.js
Labels: documentation, feature

#127 Feature/fix bfs
  node/PublicResources/js/aStar.js
  node/PublicResources/js/greedyBestFirstSearch.js
Labels: bug
