Repository KarmaKamikaze/P2-Project, pull requests merged in 2021-03, with the labels that each got.

#56 Fix CodeQL
  .github/workflows/codeql-analysis.yml
Labels: bug

#57 Weighting function
  node/PublicResources/js/weighting_function.js
Labels: feature

#74 Cytoscape network restructuring
  node/PublicResources/css/style.css
  node/PublicResources/graphPresets/GraphTest1.cyjs
  node/PublicResources/graphPresets/TestDijkstra1.cyjs
  node/PublicResources/graphPresets/TestNetwork1.cyjs
  node/PublicResources/html/index.html
  node/PublicResources/js/cytoNetwork.js
  node/PublicResources/js/cytoStylesheet.js
  node/PublicResources/js/darkMode.js
  node/PublicResources/js/dijkstra.js
  node/PublicResources/js/graphCore.js
  node/PublicResources/js/graphHelper.js
  node/PublicResources/js/pathModules.js
Labels: enhancement

#81 Feature/best first search
  node/PublicResources/js/graphCore.js
  node/PublicResources/js/greedyBestFirstSearch.js
  node/PublicResources/js/queue.js
Labels: feature
